### PR TITLE
keys added for google analytics

### PR DESCRIPTION
**Pull request by yemoski**
from my research, I need this script tag running on search.polder.info for me to have google analytics reading our site.

### CODE REVIEW

**Comment by nein09** [comment]
You do, but I think where we wanted to start was to decide whether to use Google Analytics, or something else, to collect the metrics we want. GA might be everything we need, but is there something else out that that might suit our needs better? Can you step back and take a look at, say Matomo, to see whether that one might be a good candidate?

**Comment by yemoski** [comment]
Google Analytics and Matomo have the same features to get the data we want but we might have to query them differently.
It seems like the major difference between GA and Matomo is that Matomo is open source which supports what we are trying to do. 
But, the drawback of Matomo is that, From this video (https://matomo.org/faq/on-premise/installing-matomo/), we have to set up our own Mysql server to use it. 
The other option is to use the Matomo server, we would have to pay for it (we only have a 30-day free trial).

The free version of Google Analytics provides more than enough features like real-time data, custom reporting, advanced segmentation, Flow Visualization, social reporting, conversion reporting, mobile device and app tracking, video performance measurement, multi-channel reporting, data export, and tracking API. 
In addition, We do not need to create our own server to query information.

However, the drawback of this standard version is that we have a limited amount of hits per month (10 million hits), 50,000 rows of data, and data freshness of 24 hours. Also, GA is not open source.
From these limitations, I am not sure if these affect us.


more on https://www.impactplus.com/blog/is-google-analytics-free.

Should i mention these to Karen for her input?

**Comment by nein09** [comment]
Yes, please write this up in an email to me, Karen and Chantelle - it sounds like Google Analytics is probably our best path forward, but it's good to know the pros and cons. Maybe one day we will get to over 10 million hits per month, that's a nice thing to aspire to - but we're definitely not there yet.

**Comment by yemoski** [comment]
Thanks for letting me know!!
Wishing you a great weekend.

**Pull request merged**
